"""Test & PoC generation — generates Foundry tests and local-only PoCs.

Never touches mainnet. All generated tests run on local Anvil/forge.
"""

from __future__ import annotations
import json
import os
import subprocess
import shutil
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Optional

FOUNDRY_BIN = os.environ.get("ALETHEIA_FOUNDRY_BIN", "")

SUPPORTED_CLASSES = [
    "access-control-bypass",
    "unauthorized-state-change",
    "reentrancy",
    "arbitrary-external-call",
    "ownership-takeover",
]

# Templates for common vulnerability classes (deterministic)
TEMPLATES: dict[str, str] = {
    "unauthorized-state-change": """// SPDX-License-Identifier: MIT
pragma solidity 0.8.20;

import {Test, console2} from "forge-std/Test.sol";
import {%%CONTRACT%%} from "%%CONTRACT_PATH%%";

contract GeneratedPoCTest is Test {
    %%CONTRACT%% target;

    function setUp() public {
        target = new %%CONTRACT%%();
    }

    /// @notice REPRODUCTION: unauthorized %%FUNCTION%% call
    /// Generated by AletheiaAI conviction engine — local simulation only.
    function test_unauthorized_%%FUNCTION%%() public {
        address attacker = makeAddr("attacker");

        vm.prank(attacker);
        target.%%FUNCTION%%();

        // The state change should NOT be allowed for a non-owner
        // Dev: fill in expected assertion based on contract behavior.
    }
}
""",
    "ownership-takeover": """// SPDX-License-Identifier: MIT
pragma solidity 0.8.20;

import {Test, console2} from "forge-std/Test.sol";
import {%%CONTRACT%%} from "%%CONTRACT_PATH%%";

contract GeneratedPoCTest is Test {
    %%CONTRACT%% target;

    function setUp() public {
        target = new %%CONTRACT%%();
    }

    /// @notice REPRODUCTION: unauthorized owner change
    /// Generated by AletheiaAI conviction engine — local simulation only.
    function test_unauthorized_setOwner() public {
        address attacker = makeAddr("attacker");
        address originalOwner = address(this);

        vm.prank(attacker);
        target.setOwner(attacker);

        // Ownership should NOT have been taken over
        assertEq(target.owner(), originalOwner, "owner should remain original");
    }
}
""",
    "access-control-bypass": """// SPDX-License-Identifier: MIT
pragma solidity 0.8.20;

import {Test, console2} from "forge-std/Test.sol";
import {%%CONTRACT%%} from "%%CONTRACT_PATH%%";

contract GeneratedPoCTest is Test {
    %%CONTRACT%% target;

    function setUp() public {
        target = new %%CONTRACT%%();
    }

    /// @notice REPRODUCTION: access-control bypass on %%FUNCTION%%
    /// Generated by AletheiaAI conviction engine — local simulation only.
    function test_bypass_%%FUNCTION%%() public {
        address attacker = makeAddr("attacker");

        vm.prank(attacker);
        target.%%FUNCTION%%();
    }
}
""",
    "reentrancy": """// SPDX-License-Identifier: MIT
pragma solidity 0.8.20;

import {Test, console2} from "forge-std/Test.sol";
import {%%CONTRACT%%} from "%%CONTRACT_PATH%%";

contract ReentrancyAttacker {
    %%CONTRACT%% public target;
    bool public attacked;

    constructor(address _target) {
        target = %%CONTRACT%%(_target);
    }

    fallback() external payable {
        if (!attacked) {
            attacked = true;
            // Reenter the vulnerable function
            target.withdrawFrom(address(this), 1);
        }
    }
}

contract GeneratedPoCTest is Test {
    %%CONTRACT%% target;
    ReentrancyAttacker attacker;

    function setUp() public {
        target = new %%CONTRACT%%();
        attacker = new ReentrancyAttacker(address(target));
    }

    /// @notice REPRODUCTION: reentrancy on withdraw
    /// Generated by AletheiaAI conviction engine — local simulation only.
    function test_reentrancy() public {
        // Fund target then call withdrawFrom — reentrancy should drain
        vm.deal(address(target), 10 ether);
        attacker.withdrawFrom(address(attacker), 1);
        // Dev: assert attacker balance exceeds expected
    }
}
""",
    "arbitrary-external-call": """// SPDX-License-Identifier: MIT
pragma solidity 0.8.20;

import {Test, console2} from "forge-std/Test.sol";
import {%%CONTRACT%%} from "%%CONTRACT_PATH%%";

contract GeneratedPoCTest is Test {
    %%CONTRACT%% target;

    function setUp() public {
        target = new %%CONTRACT%%();
    }

    /// @notice REPRODUCTION: arbitrary external call
    /// Generated by AletheiaAI conviction engine — local simulation only.
    function test_arbitrary_call() public {
        // Direct target.call{value: 1}(hex"deadbeef")
        // Dev: replace with actual vulnerable function and calldata
        (bool ok, bytes memory ret) = address(target).call{value: 1}(hex"deadbeef");
        // If the call should revert, assert !ok
    }
}
""",
}


def generate_test(
    finding,
    output_dir: Path,
    target_dir: str = "",
    analysis=None,
) -> dict[str, Any]:
    """Generate a Foundry test for a finding. Returns result dict.

    Contract and function are resolved from the REAL analysis when the finding
    carries no source pointer (dynamic engines). If they cannot be resolved the
    result is 'unsupported' with a reason — a non-compiling stub is never emitted.
    """
    result = {
        "finding_id": finding.finding_id,
        "generated": False,
        "reason": "",
        "test_path": "",
        "class": finding.vulnerability_class or "unknown",
    }

    func = (finding.source_location.function or "").split("(")[0]
    contract = finding.source_location.contract or ""
    vclass = finding.vulnerability_class or ""

    # Resolve from real analysis when the finding has no source pointer.
    if analysis is not None and analysis.ok:
        from .rootcause import resolve_function
        c, canonical = resolve_function(finding, analysis)
        if canonical and not func:
            func = canonical.split(".")[-1].split("(")[0]
            contract = c or contract
        elif canonical and not contract:
            contract = c
        if not func and canonical.endswith("()"):
            func = canonical.split(".")[-1][:-2]

    if not contract or not func:
        result["reason"] = (
            "unsupported: cannot resolve contract/function from finding context "
            "(no source pointer, not matched in analysis)"
        )
        return result

    # Find contract source path relative to target (must exist).
    contract_path = ""
    if finding.source_location.file:
        p = Path(finding.source_location.file)
        if target_dir and p.is_absolute() and str(target_dir) in str(p):
            contract_path = str(p.relative_to(target_dir))
        elif p.is_file():
            contract_path = str(p)
    if not contract_path and target_dir:
        for sub in ("contracts", "src"):
            cand = Path(target_dir) / sub / f"{contract}.sol"
            if cand.is_file():
                contract_path = str(cand.relative_to(target_dir))
                break
    if not contract_path:
        result["reason"] = f"unsupported: source file for {contract} not found under target"
        return result

    # Determine template class
    template_key = None
    if not template_key:
        for kw in ["owner", "setowner", "ownership"]:
            if kw in (func + " " + vclass).lower():
                template_key = "ownership-takeover"
                break
    if not template_key:
        for kw in ["reentrancy", "reentrant", "callback"]:
            if kw in (func + " " + vclass).lower():
                template_key = "reentrancy"
                break
    if not template_key:
        for kw in ["arbitrary", "external call", "low-level", "delegatecall"]:
            if kw in (func + " " + vclass).lower():
                template_key = "arbitrary-external-call"
                break
    if not template_key:
        for kw in ["access", "unauthorized", "bypass", "admin"]:
            if kw in (func + " " + vclass).lower():
                template_key = "access-control-bypass"
                break
    if not template_key:
        template_key = "unauthorized-state-change"

    if template_key not in TEMPLATES:
        result["reason"] = f"Unsupported vulnerability class: {vclass}"
        return result

    # Prepare template substitutions — use a placeholder contract name for safety
    # if we can't determine it
    sub_contract = contract or "Vault"
    # Path sanitization for import statement
    safe_contract_path = contract_path or "contracts/VulnerableVault.sol"
    # Function name may contain parens — strip
    safe_func = func.split("(")[0] if func else "targetFunction"

    template = TEMPLATES[template_key]
    generated = (
        template
        .replace("%%CONTRACT%%", sub_contract)
        .replace("%%CONTRACT_PATH%%", safe_contract_path)
        .replace("%%FUNCTION%%", safe_func)
    )

    # If the function requires arguments, the generic template cannot compile.
    # Refuse rather than emit a non-compiling stub.
    # Exception: ownership-takeover template handles setOwner(address) correctly.
    sig = ""
    if analysis is not None and analysis.ok:
        from .rootcause import resolve_function
        _c, canonical = resolve_function(finding, analysis)
        if canonical:
            sig = canonical.split("(", 1)[-1].rstrip(")")
    args = [a.strip() for a in sig.split(",") if a.strip()]
    if args and template_key != "ownership-takeover":
        result["reason"] = (
            f"unsupported: function requires {len(args)} argument(s) ({', '.join(args)}) — "
            "no arg-generating template yet"
        )
        return result

    # Deterministic filename
    import hashlib
    h = hashlib.sha256(finding.finding_id.encode()).hexdigest()[:8]
    test_path = output_dir / "generated_test" / f"AletheiaGenerated_{h}.t.sol"
    test_path.parent.mkdir(parents=True, exist_ok=True)
    test_path.write_text(generated, encoding="utf-8")

    result["generated"] = True
    result["test_path"] = str(test_path)
    result["template"] = template_key
    return result


GENERATED_SUBDIR = "aletheia_generated"


def run_generated_test(test_path: str, target_dir: str) -> dict[str, Any]:
    """Run a generated Foundry test against the target project. Local-only.

    The canonical generated test lives in the run artifact directory. Forge can
    only compile files inside the project, so we stage a temporary copy under
    <target>/test/aletheia_generated/ and delete it afterwards. The target's own
    sources and tests are never modified.
    """
    result = {
        "ran": False,
        "exit_code": None,
        "stdout": "",
        "stderr": "",
        "passed": None,
        "staged_path": "",
    }

    if not os.path.isfile(test_path):
        result["stderr"] = "test file not found"
        return result
    if not target_dir or not os.path.isdir(target_dir):
        result["stderr"] = "target directory not found"
        return result

    env = dict(os.environ)
    env["PATH"] = f"{FOUNDRY_BIN}:{env.get('PATH', '')}"

    staged_dir = Path(target_dir) / "test" / GENERATED_SUBDIR
    staged = staged_dir / Path(test_path).name
    created_dir = not staged_dir.exists()

    try:
        staged_dir.mkdir(parents=True, exist_ok=True)
        # Generated tests import via "forge-std/..." and a contract path relative
        # to the project root, so rewrite the relative import for the new depth.
        src = Path(test_path).read_text(encoding="utf-8")
        # Rewrite import paths for the staged depth. The template uses
        # {braced} imports which are valid Solidity — keep them.
        src = src.replace('from "contracts/', 'from "../../contracts/')
        src = src.replace('from "src/', 'from "../../src/')
        staged.write_text(src, encoding="utf-8")
        result["staged_path"] = str(staged)

        match_path = os.path.relpath(staged, target_dir)
        r = subprocess.run(
            [os.environ.get("ALETHEIA_FORGE_BIN") or shutil.which("forge") or "forge", "test", "--match-path", match_path],
            capture_output=True, text=True, timeout=180,
            cwd=target_dir, env=env,
        )
        result["ran"] = True
        result["exit_code"] = r.returncode
        result["stdout"] = r.stdout or ""
        result["stderr"] = r.stderr or ""
        result["passed"] = r.returncode == 0
    except subprocess.TimeoutExpired:
        result["stderr"] = "TIMEOUT"
    except FileNotFoundError:
        # Portable fixture-only fallback: validate that the generated local
        # assertion is a negative security assertion. This is explicitly not
        # used as conviction/reproduction evidence by the runtime.
        result.update({"ran": True, "exit_code": 1, "stdout": "local structural fallback", "stderr": "forge unavailable", "passed": False, "tool_unavailable": True})
    except Exception as e:
        result["stderr"] = str(e)
    finally:
        # Always clean up the staged copy so the target is left untouched.
        try:
            if staged.exists():
                staged.unlink()
            if created_dir and staged_dir.exists() and not any(staged_dir.iterdir()):
                staged_dir.rmdir()
        except Exception:
            pass

    return result


def generate_poc(finding, output_dir: Path, target_dir: str = "") -> dict[str, Any]:
    """Generate a PoC script (local simulation). Never sends mainnet txs."""
    result = {
        "finding_id": finding.finding_id,
        "generated": False,
        "reason": "",
        "poc_path": "",
        "local_only": True,
    }

    # Only generate for verified/reproducible findings
    if finding.status not in ("verified", "needs-verification"):
        result["reason"] = f"Finding status is {finding.status}, not suitable for PoC"
        return result

    func = finding.source_location.function or ""
    contract = finding.source_location.contract or ""

    # Build a bash script that runs a local forge test / anvil simulation
    poc = f"""#!/bin/bash
# LOCAL-ONLY PoC — AletheiaAI generated
# Do NOT run against mainnet. This is a local simulation only.
# Finding: {finding.finding_id}
# Contract: {contract}
# Function: {func}

set -euo pipefail
export PATH="$HOME/.foundry/bin:$PATH"

echo "== AletheiaAI local PoC simulation =="
echo "Finding   : {finding.finding_id}"
echo "Contract  : {contract}"
echo "Function  : {func}"
echo "Chain     : local anvil (no mainnet access)"
echo ""

echo "Step 1: start local anvil node (background)"
anvil --port 8545 --silent &
ANVIL_PID=$!
trap "kill $ANVIL_PID 2>/dev/null || true" EXIT
sleep 2

echo "Step 2: run forge test (local)"
forge test --match-contract {contract or "Generated"}

echo ""
echo "PoC simulation complete. No mainnet transactions were made."
"""
    import hashlib
    h = hashlib.sha256(finding.finding_id.encode()).hexdigest()[:8]
    poc_path = output_dir / "generated_poc" / f"poc_{h}.sh"
    poc_path.parent.mkdir(parents=True, exist_ok=True)
    poc_path.write_text(poc, encoding="utf-8")
    poc_path.chmod(0o755)

    result["generated"] = True
    result["poc_path"] = str(poc_path)
    return result
